/**
 * Code Review Agent — GitHub Copilot SDK
 *
 * Analyzes source code for quality issues, style violations,
 * error-handling gaps, and maintainability concerns.
 *
 * Usage:  npx tsx code-review-agent.ts
 */

import { CopilotClient, defineTool, approveAll } from "@github/copilot-sdk";
import * as readline from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";

// ---------------------------------------------------------------------------
// Tools
// ---------------------------------------------------------------------------

const analyzeCode = defineTool("analyze_code", {
  description:
    "Analyze a code snippet for quality issues including style, complexity, error handling, and maintainability",
  parameters: {
    type: "object" as const,
    properties: {
      code: {
        type: "string",
        description: "The source code to analyze",
      },
      language: {
        type: "string",
        description: "Programming language of the code (e.g. javascript, typescript, python)",
      },
      focus: {
        type: "string",
        description:
          "Specific area to focus on: style, complexity, error-handling, naming, performance, or all",
        enum: ["style", "complexity", "error-handling", "naming", "performance", "all"],
      },
    },
    required: ["code", "language"],
  },
  handler: async ({
    code,
    language,
    focus,
  }: {
    code: string;
    language: string;
    focus?: string;
  }) => {
    const focusArea = focus ?? "all";
    const lines = code.split("\n");
    const findings: string[] = [];

    // Detect common quality issues
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const lineNum = i + 1;

      if (/console\.(log|debug|info)\(/.test(line)) {
        findings.push(`Line ${lineNum}: Debug logging left in code — remove or replace with a logger`);
      }
      if (/\bvar\b/.test(line)) {
        findings.push(`Line ${lineNum}: Use 'const' or 'let' instead of 'var'`);
      }
      if (line.length > 120) {
        findings.push(`Line ${lineNum}: Line exceeds 120 characters (${line.length} chars)`);
      }
      if (/\/\/\s*TODO|\/\/\s*FIXME|\/\/\s*HACK/i.test(line)) {
        findings.push(`Line ${lineNum}: Unresolved TODO/FIXME/HACK comment`);
      }
      if (/\bcatch\s*\(\s*\w+\s*\)\s*\{\s*\}/.test(line)) {
        findings.push(`Line ${lineNum}: Empty catch block — handle or rethrow the error`);
      }
    }

    // Nesting depth check
    let maxDepth = 0;
    let depth = 0;
    for (const line of lines) {
      depth += (line.match(/{/g) || []).length;
      depth -= (line.match(/}/g) || []).length;
      maxDepth = Math.max(maxDepth, depth);
    }
    if (maxDepth > 4) {
      findings.push(`Code has nesting depth of ${maxDepth} — consider extracting functions`);
    }

    return {
      language,
      focus: focusArea,
      totalLines: lines.length,
      findingsCount: findings.length,
      findings,
      summary:
        findings.length === 0
          ? "No quality issues detected."
          : `Found ${findings.length} quality issue(s). Review the findings above.`,
    };
  },
});

const prepareReviewComment = defineTool("prepare_review_comment", {
  description:
    "Prepare a structured code review comment in markdown format suitable for a pull request",
  parameters: {
    type: "object" as const,
    properties: {
      findings: {
        type: "array",
        items: { type: "string" },
        description: "List of code review findings",
      },
      severity: {
        type: "string",
        description: "Overall severity: low, medium, high, or critical",
        enum: ["low", "medium", "high", "critical"],
      },
      filename: {
        type: "string",
        description: "Name of the reviewed file",
      },
    },
    required: ["findings", "severity"],
  },
  handler: async ({
    findings,
    severity,
    filename,
  }: {
    findings: string[];
    severity: string;
    filename?: string;
  }) => {
    const icon =
      severity === "critical"
        ? "🔴"
        : severity === "high"
          ? "🟠"
          : severity === "medium"
            ? "🟡"
            : "🟢";

    const header = filename
      ? `## ${icon} Code Review — \`${filename}\``
      : `## ${icon} Code Review`;

    const body = findings.map((f, i) => `${i + 1}. ${f}`).join("\n");

    const comment = `${header}

**Severity:** ${severity.toUpperCase()}
**Findings:** ${findings.length}

### Details

${body}

---
*Generated by Copilot SDK Code Review Agent*
`;

    return { markdown: comment, severity, findingsCount: findings.length };
  },
});

// ---------------------------------------------------------------------------
// Agent
// ---------------------------------------------------------------------------

const SYSTEM_PROMPT = `You are an expert code reviewer. When the user provides code:

1. Use the analyze_code tool to perform a detailed quality analysis.
2. Summarize findings by category (style, complexity, error-handling, naming, performance).
3. Use the prepare_review_comment tool to produce a structured markdown review.
4. Suggest specific, actionable fixes for every finding.

Rules:
- Be constructive and specific — cite line numbers.
- Prioritize findings by severity (critical > high > medium > low).
- If no issues are found, say so clearly.
- Always include a "What went well" section to highlight good practices.`;

async function main(): Promise<void> {
  console.log("🔍 Code Review Agent starting...\n");

  const client = new CopilotClient();
  const model = process.env.COPILOT_MODEL ?? "gpt-4o";

  const session = await client.createSession({
    model,
    streaming: true,
    tools: [analyzeCode, prepareReviewComment],
    mcpServers: {
      github: {
        type: "http",
        url: "https://api.githubcopilot.com/mcp/",
        tools: ["*"],
      },
    },
    systemMessage: { mode: "append", content: SYSTEM_PROMPT },
    onPermissionRequest: approveAll,
  });

  console.log("Tools registered:");
  console.log("  - analyze_code: Analyze a code snippet for quality issues");
  console.log("  - prepare_review_comment: Prepare a structured review comment\n");

  // Stream assistant responses to stdout
  session.on("assistant.message_delta", (event) => {
    if (event.data?.deltaContent) {
      process.stdout.write(event.data.deltaContent);
    }
  });

  session.on("tool.execution_start", (event) => {
    console.log(`\n⚙️  Calling tool: ${event.data.toolName}...`);
  });

  session.on("tool.execution_complete", (event) => {
    console.log(`✅ Tool completed: ${event.data.toolCallId}\n`);
  });

  // Interactive REPL with automatic multi-line paste detection
  const rl = readline.createInterface({ input, output });
  console.log("Type a prompt and press Enter to send (pasted multi-line input is auto-detected).");
  console.log("Type 'exit' to quit.\n");

  // Send an initial greeting so the agent introduces itself
  process.stdout.write("Assistant: ");
  await session.sendAndWait({
    prompt: "Hello! Please introduce yourself and explain how you can help review code.",
  }, 120000);
  console.log("\n");

  // Collect input lines; pasted text arrives within ms, so a short
  // timeout after the last line distinguishes paste from typing.
  const PASTE_DELAY_MS = 150;
  let done = false;

  const collectInput = (): Promise<string | null> =>
    new Promise((resolve) => {
      const lines: string[] = [];
      let timer: ReturnType<typeof setTimeout> | null = null;

      const flush = () => {
        rl.removeListener("line", onLine);
        rl.removeListener("close", onClose);
        const text = lines.join("\n").trim();
        resolve(text || null);
      };

      const onLine = (line: string) => {
        if (lines.length === 0) {
          if (line.trim().toLowerCase() === "exit") { done = true; resolve(null); rl.close(); return; }
          if (line.trim() === "") { resolve(""); return; }
          process.stdout.write("> ");
        }
        lines.push(line);
        if (timer) clearTimeout(timer);
        timer = setTimeout(flush, PASTE_DELAY_MS);
      };

      const onClose = () => { done = true; resolve(null); };

      rl.on("line", onLine);
      rl.on("close", onClose);
    });

  while (!done) {
    process.stdout.write("> ");
    const prompt = await collectInput();
    if (prompt === null) { console.log("\n👋 Shutting down Code Review Agent..."); break; }
    if (prompt === "") continue;
    console.log("");
    await session.sendAndWait({ prompt }, 120000);    console.log("\n");
  }

  rl.close();
  await client.stop();
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
